name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: |
        chmod +x ./unit-test.sh
        ./unit-test.sh
    - name: Run full tests
      run: |
        chmod +x ./full-test.sh
        ./full-test.sh

